### ISSUE TITLE
Peer Review Suggestion: Speed up build

### ISSUE THREAD

**Issue by aaronjenson** [RecycleRightCSE403/RecycleRight#34]
From the peer review feedback:

> If possible, either scale back the implementation with a boolean flag that makes it faster/easier to run
on low-end machines, or optimize your code or build. The laptop we tried to build this on had a Core i7
and it struggled to finish building and running tests in a reasonable amount of time.

**Comment by DefDen** [comment]
Unfortunately this is out of scope of our project. We believe that this optimization would be too difficult and not a priority given our limited resources.
